# Configuration file for Beckhoff EL1008
vendor_id: 0x00000002
product_id: 0x03f03052
tpdo:  # TxPDO
  - index: 0x1a00
    channels:
      # - {index: 0x6000, sub_index: 1, type: bool, mask: 1, state_interface: lubrication_state}
      - {index: 0x6000, sub_index: 1, type: bool, mask: 1, state_interface: limit_switch_end}
  - index: 0x1a01
    channels:
      - {index: 0x6010, sub_index: 1, type: bool, mask: 2, state_interface: limit_switch_homing}
  - index: 0x1a02
    channels:
      - {index: 0x6020, sub_index: 1, type: bool, mask: 4, state_interface: lubrication_state}
  - index: 0x1a03
    channels:
      - {index: 0x6030, sub_index: 1, type: bool, mask: 8, state_interface: d_input.3}
  - index: 0x1a04
    channels:
      - {index: 0x6040, sub_index: 1, type: bool, mask: 16, state_interface: d_input.4}
  - index: 0x1a05
    channels:
      - {index: 0x6050, sub_index: 1, type: bool, mask: 32, state_interface: d_input.5}
  - index: 0x1a06
    channels:
      - {index: 0x6060, sub_index: 1, type: bool, mask: 64, state_interface: d_input.6}
  - index: 0x1a07
    channels:
      - {index: 0x6070, sub_index: 1, type: bool, mask: 128, state_interface: d_input.7}

sm:  # Sync Manager
#  - {index: 0, type: output, pdo: ~,    watchdog: disable}
#  - {index: 1, type: input,  pdo: ~,    watchdog: disable}
#  - {index: 2, type: output, pdo: ~,    watchdog: disable}
  - {index: 3, type: input,  pdo: tpdo, watchdog: enable}
